In [ ]:
import yfinance as yf

ticker = yf.Ticker("INFY.NS")

history = ticker.history(period="10y")
info = ticker.info

In [ ]:
history.head()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2016-08-11 00:00:00+05:30,408.808881,413.835393,406.371239,407.164886,5038552,0.0,0.0
2016-08-12 00:00:00+05:30,406.295682,407.712926,400.607788,401.571533,7449928,0.0,0.0
2016-08-16 00:00:00+05:30,393.805038,399.870863,388.513991,397.508789,16429408,0.0,0.0
2016-08-17 00:00:00+05:30,396.809589,397.830033,389.458832,390.517059,6599316,0.0,0.0
2016-08-18 00:00:00+05:30,391.726380,392.708994,386.057402,386.775482,8434000,0.0,0.0

In [ ]:
print(info["marketCap"])
print(info["beta"])
print(info["sharesOutstanding"])

4822481764352
0.107
4050123578

In [ ]:
history.to_csv("infosys_stock_history.csv")

In [ ]:
#@title Import Libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings

warnings.filterwarnings("ignore")

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 200)

plt.style.use("ggplot")

In [ ]:
#@title Load Excel Workbook

excel_file = "Infosys.xlsx"

xls = pd.ExcelFile(excel_file)

print("Sheets in workbook:")
print(xls.sheet_names)

Sheets in workbook:
['Profit & Loss', 'Quarters', 'Balance Sheet', 'Cash Flow', 'Customization', 'Data Sheet']

In [ ]:
#@title Load Financial Statements

income_statement = pd.read_excel(
    excel_file,
    sheet_name="Profit & Loss"
)

balance_sheet = pd.read_excel(
    excel_file,
    sheet_name="Balance Sheet"
)

cash_flow = pd.read_excel(
    excel_file,
    sheet_name="Cash Flow"
)

print("Income Statement Shape :", income_statement.shape)
print("Balance Sheet Shape    :", balance_sheet.shape)
print("Cash Flow Shape        :", cash_flow.shape)

Income Statement Shape : (24, 14)
Balance Sheet Shape    : (23, 11)
Cash Flow Shape        : (6, 11)

In [ ]:
#@title Preview Raw Data

print("Income Statement")
display(income_statement.head())

print("\nBalance Sheet")
display(balance_sheet.head())

print("\nCash Flow")
display(cash_flow.head())

Income Statement

,INFOSYS LTD,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,SCREENER.IN,Unnamed: 13
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Narration,2017-03-31 00:00:00,2018-03-31 00:00:00,2019-03-31 00:00:00,2020-03-31 00:00:00,2021-03-31 00:00:00,2022-03-31 00:00:00,2023-03-31 00:00:00,2024-03-31 00:00:00,2025-03-31 00:00:00,2026-03-31 00:00:00,Trailing,Best Case,Worst Case
2,Sales,68484,70522,82675,90791,100472,121641,146767,153670,162990,178650,184582,195814.605191,191150.266679
3,Expenses,49880,51700,62505,68524,72583,90150,111637,117245,123754,136370,140837,149188.107945,145848.620712
4,Operating Profit,18604,18822,20170,22267,27889,31491,35130,36425,39236,42280,43745,46626.497246,45301.645967

Balance Sheet

,INFOSYS LTD,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,SCREENER.IN,Unnamed: 10
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Narration,2017-03-31 00:00:00,2018-03-31 00:00:00,2019-03-31 00:00:00,2020-03-31 00:00:00,2021-03-31 00:00:00,2022-03-31 00:00:00,2023-03-31 00:00:00,2024-03-31 00:00:00,2025-03-31 00:00:00,2026-03-31 00:00:00
2,Equity Share Capital,1144,1088,2170,2122,2124,2098,2069,2071,2073,2024
3,Reserves,67838,63835,62778,63328,74227,73252,73338,86045,93745,90828
4,Borrowings,0,0,0,4633,5325,5474,8299,8359,8227,9176

Cash Flow

,INFOSYS LTD,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,SCREENER.IN,Unnamed: 10
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Narration,2017-03-31 00:00:00,2018-03-31 00:00:00,2019-03-31 00:00:00,2020-03-31 00:00:00,2021-03-31 00:00:00,2022-03-31 00:00:00,2023-03-31 00:00:00,2024-03-31 00:00:00,2025-03-31 00:00:00,2026-03-31 00:00:00
2,Cash from Operating Activity,11531,13218,14841,17003,23224,23885,22467,25210,35694,33986
3,Cash from Investing Activity,-14664,4533,-632,-331,-7373,-6485,-1071,-5093,-1864,3546
4,Cash from Financing Activity,-6939,-20505,-14512,-17591,-9786,-24642,-26695,-17504,-24161,-39786

In [ ]:
#@title Check Missing Values

print("Income Statement")
display(income_statement.isna().sum())

print("\nBalance Sheet")
display(balance_sheet.isna().sum())

print("\nCash Flow")
display(cash_flow.isna().sum())

Income Statement

INFOSYS LTD    8
Unnamed: 1     9
Unnamed: 2     9
Unnamed: 3     9
Unnamed: 4     9
Unnamed: 5     9
Unnamed: 6     5
Unnamed: 7     5
Unnamed: 8     5
Unnamed: 9     5
Unnamed: 10    5
Unnamed: 11    6
SCREENER.IN    7
Unnamed: 13    7
dtype: int64

Balance Sheet

INFOSYS LTD    5
Unnamed: 1     6
Unnamed: 2     5
Unnamed: 3     5
Unnamed: 4     5
Unnamed: 5     5
Unnamed: 6     5
Unnamed: 7     5
Unnamed: 8     5
SCREENER.IN    5
Unnamed: 10    5
dtype: int64

Cash Flow

INFOSYS LTD    1
Unnamed: 1     1
Unnamed: 2     1
Unnamed: 3     1
Unnamed: 4     1
Unnamed: 5     1
Unnamed: 6     1
Unnamed: 7     1
Unnamed: 8     1
SCREENER.IN    1
Unnamed: 10    1
dtype: int64

In [ ]:
#@title Check Data Types

print("Income Statement")
display(income_statement.dtypes)

print("\nBalance Sheet")
display(balance_sheet.dtypes)

print("\nCash Flow")
display(cash_flow.dtypes)

Income Statement

INFOSYS LTD    object
Unnamed: 1     object
Unnamed: 2     object
Unnamed: 3     object
Unnamed: 4     object
Unnamed: 5     object
Unnamed: 6     object
Unnamed: 7     object
Unnamed: 8     object
Unnamed: 9     object
Unnamed: 10    object
Unnamed: 11    object
SCREENER.IN    object
Unnamed: 13    object
dtype: object

Balance Sheet

INFOSYS LTD    object
Unnamed: 1     object
Unnamed: 2     object
Unnamed: 3     object
Unnamed: 4     object
Unnamed: 5     object
Unnamed: 6     object
Unnamed: 7     object
Unnamed: 8     object
SCREENER.IN    object
Unnamed: 10    object
dtype: object

Cash Flow

INFOSYS LTD    object
Unnamed: 1     object
Unnamed: 2     object
Unnamed: 3     object
Unnamed: 4     object
Unnamed: 5     object
Unnamed: 6     object
Unnamed: 7     object
Unnamed: 8     object
SCREENER.IN    object
Unnamed: 10    object
dtype: object

In [ ]:
#@title Remove Completely Empty Rows

income_statement = income_statement.dropna(how="all")
balance_sheet = balance_sheet.dropna(how="all")
cash_flow = cash_flow.dropna(how="all")

print("Cleaning Complete")

Cleaning Complete

In [ ]:
#@title Remove Completely Empty Columns

income_statement = income_statement.dropna(axis=1, how="all")
balance_sheet = balance_sheet.dropna(axis=1, how="all")
cash_flow = cash_flow.dropna(axis=1, how="all")

In [ ]:
#@title Check Duplicate Rows

print("Income Statement :", income_statement.duplicated().sum())
print("Balance Sheet    :", balance_sheet.duplicated().sum())
print("Cash Flow        :", cash_flow.duplicated().sum())

Income Statement : 0
Balance Sheet    : 1
Cash Flow        : 0

In [ ]:
#@title Remove Duplicate Rows

income_statement = income_statement.drop_duplicates()
balance_sheet = balance_sheet.drop_duplicates()
cash_flow = cash_flow.drop_duplicates()

In [ ]:
#@title Display Dataset Information

print("Income Statement")
income_statement.info()

print("\nBalance Sheet")
balance_sheet.info()

print("\nCash Flow")
cash_flow.info()

Income Statement
<class 'pandas.core.frame.DataFrame'>
Index: 20 entries, 1 to 23
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   INFOSYS LTD  16 non-null     object
 1   Unnamed: 1   15 non-null     object
 2   Unnamed: 2   15 non-null     object
 3   Unnamed: 3   15 non-null     object
 4   Unnamed: 4   15 non-null     object
 5   Unnamed: 5   15 non-null     object
 6   Unnamed: 6   19 non-null     object
 7   Unnamed: 7   19 non-null     object
 8   Unnamed: 8   19 non-null     object
 9   Unnamed: 9   19 non-null     object
 10  Unnamed: 10  19 non-null     object
 11  Unnamed: 11  18 non-null     object
 12  SCREENER.IN  17 non-null     object
 13  Unnamed: 13  17 non-null     object
dtypes: object(14)
memory usage: 2.3+ KB

Balance Sheet
<class 'pandas.core.frame.DataFrame'>
Index: 17 entries, 1 to 22
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   INFOSYS LTD  17 non-null     object
 1   Unnamed: 1   16 non-null     object
 2   Unnamed: 2   17 non-null     object
 3   Unnamed: 3   17 non-null     object
 4   Unnamed: 4   17 non-null     object
 5   Unnamed: 5   17 non-null     object
 6   Unnamed: 6   17 non-null     object
 7   Unnamed: 7   17 non-null     object
 8   Unnamed: 8   17 non-null     object
 9   SCREENER.IN  17 non-null     object
 10  Unnamed: 10  17 non-null     object
dtypes: object(11)
memory usage: 1.6+ KB

Cash Flow
<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 1 to 5
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   INFOSYS LTD  5 non-null      object
 1   Unnamed: 1   5 non-null      object
 2   Unnamed: 2   5 non-null      object
 3   Unnamed: 3   5 non-null      object
 4   Unnamed: 4   5 non-null      object
 5   Unnamed: 5   5 non-null      object
 6   Unnamed: 6   5 non-null      object
 7   Unnamed: 7   5 non-null      object
 8   Unnamed: 8   5 non-null      object
 9   SCREENER.IN  5 non-null      object
 10  Unnamed: 10  5 non-null      object
dtypes: object(11)
memory usage: 480.0+ bytes

In [ ]:
#@title Export Clean Raw Statements

income_statement.to_csv(
    "income_statement_raw.csv",
    index=False
)

balance_sheet.to_csv(
    "balance_sheet_raw.csv",
    index=False
)

cash_flow.to_csv(
    "cash_flow_raw.csv",
    index=False
)

print("Raw financial statements exported successfully.")

Raw financial statements exported successfully.

In [ ]:
#@title Promote First Data Row to Header

def clean_statement(df):

    # Make first row the header
    df.columns = df.iloc[0]

    # Remove the header row
    df = df.iloc[1:].reset_index(drop=True)

    return df

income_statement = clean_statement(income_statement)
balance_sheet = clean_statement(balance_sheet)
cash_flow = clean_statement(cash_flow)

In [ ]:
#@title Preview Cleaned Statements

print("Income Statement")
display(income_statement.head())

print("\nBalance Sheet")
display(balance_sheet.head())

print("\nCash Flow")
display(cash_flow.head())

Income Statement

1,Narration,2017-03-31 00:00:00,2018-03-31 00:00:00,2019-03-31 00:00:00,2020-03-31 00:00:00,2021-03-31 00:00:00,2022-03-31 00:00:00,2023-03-31 00:00:00,2024-03-31 00:00:00,2025-03-31 00:00:00,2026-03-31 00:00:00,Trailing,Best Case,Worst Case
0,Sales,68484,70522,82675,90791,100472,121641,146767,153670,162990,178650,184582,195814.605191,191150.266679
1,Expenses,49880,51700,62505,68524,72583,90150,111637,117245,123754,136370,140837,149188.107945,145848.620712
2,Operating Profit,18604,18822,20170,22267,27889,31491,35130,36425,39236,42280,43745,46626.497246,45301.645967
3,Other Income,3050,3311,2882,2803,2201,2295,2701,4711,3600,3033,2975,0,0
4,Depreciation,1703,1863,2011,2893,3267,3476,4225,4678,4812,4902,5007,5007,5007

Balance Sheet

1,Narration,2017-03-31 00:00:00,2018-03-31 00:00:00,2019-03-31 00:00:00,2020-03-31 00:00:00,2021-03-31 00:00:00,2022-03-31 00:00:00,2023-03-31 00:00:00,2024-03-31 00:00:00,2025-03-31 00:00:00,2026-03-31 00:00:00
0,Equity Share Capital,1144,1088,2170,2122,2124,2098,2069,2071,2073,2024
1,Reserves,67838,63835,62778,63328,74227,73252,73338,86045,93745,90828
2,Borrowings,0,0,0,4633,5325,5474,8299,8359,8227,9176
3,Other Liabilities,14166,14426,19118,21717,25835,35905,40890,39545,43750,52260
4,Total,83148,79349,84066,91800,107511,116729,124596,136020,147795,154288

Cash Flow

1,Narration,2017-03-31 00:00:00,2018-03-31 00:00:00,2019-03-31 00:00:00,2020-03-31 00:00:00,2021-03-31 00:00:00,2022-03-31 00:00:00,2023-03-31 00:00:00,2024-03-31 00:00:00,2025-03-31 00:00:00,2026-03-31 00:00:00
0,Cash from Operating Activity,11531,13218,14841,17003,23224,23885,22467,25210,35694,33986
1,Cash from Investing Activity,-14664,4533,-632,-331,-7373,-6485,-1071,-5093,-1864,3546
2,Cash from Financing Activity,-6939,-20505,-14512,-17591,-9786,-24642,-26695,-17504,-24161,-39786
3,Net Cash Flow,-10072,-2754,-303,-919,6065,-7242,-5299,2613,9669,-2254

In [ ]:
#@title Rename First Column

income_statement.rename(
    columns={income_statement.columns[0]:"Metric"},
    inplace=True
)

balance_sheet.rename(
    columns={balance_sheet.columns[0]:"Metric"},
    inplace=True
)

cash_flow.rename(
    columns={cash_flow.columns[0]:"Metric"},
    inplace=True
)

In [ ]:
#@title Keep Historical Years Only

income_statement = income_statement.iloc[:, :11]

balance_sheet = balance_sheet.iloc[:, :11]

cash_flow = cash_flow.iloc[:, :11]

In [ ]:
#@title Convert Year Columns

for df in [income_statement, balance_sheet, cash_flow]:

    df.columns = [
        col.year if hasattr(col, "year") else col
        for col in df.columns
    ]

In [ ]:
#@title Convert Financial Values to Numeric

for df in [income_statement, balance_sheet, cash_flow]:

    for col in df.columns[1:]:

        df[col] = (
            df[col]
            .astype(str)
            .str.replace(",", "")
            .str.replace("₹", "")
            .str.strip()
        )

        df[col] = pd.to_numeric(df[col], errors="coerce")

In [ ]:
#@title Dataset Information After Cleaning

print(income_statement.info())

print(balance_sheet.info())

print(cash_flow.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Metric  15 non-null     object
 1   2017    14 non-null     float64
 2   2018    14 non-null     float64
 3   2019    14 non-null     float64
 4   2020    14 non-null     float64
 5   2021    14 non-null     float64
 6   2022    14 non-null     float64
 7   2023    17 non-null     float64
 8   2024    17 non-null     float64
 9   2025    17 non-null     float64
 10  2026    17 non-null     float64
dtypes: float64(10), object(1)
memory usage: 1.8+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Metric  16 non-null     object
 1   2017    15 non-null     float64
 2   2018    16 non-null     float64
 3   2019    16 non-null     float64
 4   2020    16 non-null     float64
 5   2021    16 non-null     float64
 6   2022    16 non-null     float64
 7   2023    16 non-null     float64
 8   2024    16 non-null     float64
 9   2025    16 non-null     float64
 10  2026    16 non-null     float64
dtypes: float64(10), object(1)
memory usage: 1.5+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Metric  4 non-null      object
 1   2017    4 non-null      int64
 2   2018    4 non-null      int64
 3   2019    4 non-null      int64
 4   2020    4 non-null      int64
 5   2021    4 non-null      int64
 6   2022    4 non-null      int64
 7   2023    4 non-null      int64
 8   2024    4 non-null      int64
 9   2025    4 non-null      int64
 10  2026    4 non-null      int64
dtypes: int64(10), object(1)
memory usage: 484.0+ bytes
None

In [ ]:
#@title Final Preview

display(income_statement)

display(balance_sheet)

display(cash_flow)

,Metric,2017,2018,2019,2020,2021,2022,2023,2024,2025,2026
0,Sales,68484.000000,70522.000000,82675.000000,90791.000000,100472.000000,121641.000000,146767.000000,153670.000000,162990.000000,178650.000000
1,Expenses,49880.000000,51700.000000,62505.000000,68524.000000,72583.000000,90150.000000,111637.000000,117245.000000,123754.000000,136370.000000
2,Operating Profit,18604.000000,18822.000000,20170.000000,22267.000000,27889.000000,31491.000000,35130.000000,36425.000000,39236.000000,42280.000000
3,Other Income,3050.000000,3311.000000,2882.000000,2803.000000,2201.000000,2295.000000,2701.000000,4711.000000,3600.000000,3033.000000
4,Depreciation,1703.000000,1863.000000,2011.000000,2893.000000,3267.000000,3476.000000,4225.000000,4678.000000,4812.000000,4902.000000
5,Interest,0.000000,0.000000,0.000000,170.000000,195.000000,200.000000,284.000000,470.000000,416.000000,416.000000
6,Profit before tax,19951.000000,20270.000000,21041.000000,22007.000000,26628.000000,30110.000000,33322.000000,35988.000000,37608.000000,39995.000000
7,Tax,5598.000000,4241.000000,5631.000000,5368.000000,7205.000000,7964.000000,9214.000000,9740.000000,10858.000000,10521.000000
8,Net profit,14353.000000,16029.000000,15404.000000,16594.000000,19351.000000,22110.000000,24095.000000,26233.000000,26713.000000,29440.000000
9,EPS,31.243606,36.694748,35.258303,38.962198,45.417420,52.559013,58.079834,63.198343,64.317531,72.590985
10,Price to earning,16.359507,15.421825,21.097158,16.464677,30.121702,36.280171,24.585986,23.703944,24.420247,17.228035
11,Price,511.130000,565.900000,743.850000,641.500000,1368.050000,1906.850000,1427.950000,1498.050000,1570.650000,1250.600000
12,RATIOS:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Dividend Payout,0.410479,0.590530,0.598708,0.447571,0.592714,0.588313,0.583905,0.726307,0.667383,0.660000
14,OPM,0.271655,0.266895,0.243967,0.245256,0.277580,0.258885,0.239359,0.237034,0.240726,0.236664
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.112419,0.116360,0.121997,0.067722
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.248426,0.245783,0.241662,0.238116
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.967277,23.595194,23.695863,20.327255

,Metric,2017,2018,2019,2020,2021,2022,2023,2024,2025,2026
0,Equity Share Capital,1144.000000,1088.000000,2170.000000,2122.000000,2124.000000,2098.000000,2069.000000,2071.000000,2073.000000,2024.000000
1,Reserves,67838.000000,63835.000000,62778.000000,63328.000000,74227.000000,73252.000000,73338.000000,86045.000000,93745.000000,90828.000000
2,Borrowings,0.000000,0.000000,0.000000,4633.000000,5325.000000,5474.000000,8299.000000,8359.000000,8227.000000,9176.000000
3,Other Liabilities,14166.000000,14426.000000,19118.000000,21717.000000,25835.000000,35905.000000,40890.000000,39545.000000,43750.000000,52260.000000
4,Total,83148.000000,79349.000000,84066.000000,91800.000000,107511.000000,116729.000000,124596.000000,136020.000000,147795.000000,154288.000000
5,Net Block,14179.000000,12574.000000,15710.000000,23789.000000,25505.000000,25800.000000,29225.000000,27622.000000,30961.000000,33770.000000
6,Capital Work in Progress,1365.000000,1606.000000,1388.000000,954.000000,922.000000,416.000000,288.000000,293.000000,814.000000,526.000000
7,Investments,16423.000000,12163.000000,11261.000000,8792.000000,14205.000000,20324.000000,19478.000000,24623.000000,23541.000000,21880.000000
8,Other Assets,51181.000000,53006.000000,55707.000000,58265.000000,66879.000000,70189.000000,75605.000000,83482.000000,92479.000000,98112.000000
9,Working Capital,37015.000000,38580.000000,36589.000000,36548.000000,41044.000000,34284.000000,34715.000000,43937.000000,48729.000000,45852.000000
10,Debtors,12322.000000,13142.000000,14827.000000,18487.000000,19294.000000,22698.000000,25424.000000,30193.000000,31158.000000,35234.000000
11,Inventory,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
12,Debtor Days,65.672712,68.018916,65.459389,74.321849,70.092265,68.108368,63.227837,71.715006,69.775262,71.986622
13,Inventory Turnover,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
14,Return on Equity,0.208069,0.246892,0.237174,0.253537,0.253448,0.293431,0.319533,0.297710,0.278789,0.317064
15,Return on Capital Emp,NaN,0.302752,0.324029,0.328473,0.353495,0.373046,0.408509,0.404682,0.379254,0.392201

,Metric,2017,2018,2019,2020,2021,2022,2023,2024,2025,2026
0,Cash from Operating Activity,11531,13218,14841,17003,23224,23885,22467,25210,35694,33986
1,Cash from Investing Activity,-14664,4533,-632,-331,-7373,-6485,-1071,-5093,-1864,3546
2,Cash from Financing Activity,-6939,-20505,-14512,-17591,-9786,-24642,-26695,-17504,-24161,-39786
3,Net Cash Flow,-10072,-2754,-303,-919,6065,-7242,-5299,2613,9669,-2254

In [ ]:
#@title Create Metric Lookup Function

def get_metric(df, metric):

    row = df[df["Metric"] == metric]

    if row.empty:
        return None

    return row.iloc[0, 1:]

In [ ]:
#@title Build Income Statement Dataset

income_df = pd.DataFrame({

    "Year": income_statement.columns[1:],

    "Revenue": get_metric(income_statement, "Sales").values,

    "Operating_Expenses": get_metric(income_statement, "Expenses").values,

    "Operating_Profit": get_metric(income_statement, "Operating Profit").values,

    "Other_Income": get_metric(income_statement, "Other Income").values,

    "Depreciation": get_metric(income_statement, "Depreciation").values,

    "Interest": get_metric(income_statement, "Interest").values,

    "PBT": get_metric(income_statement, "Profit before tax").values,

    "Tax": get_metric(income_statement, "Tax").values,

    "Net_Income": get_metric(income_statement, "Net profit").values,

    "EPS": get_metric(income_statement, "EPS").values

})

income_df

,Year,Revenue,Operating_Expenses,Operating_Profit,Other_Income,Depreciation,Interest,PBT,Tax,Net_Income,EPS
0,2017,68484.0,49880.0,18604.0,3050.0,1703.0,0.0,19951.0,5598.0,14353.0,31.243606
1,2018,70522.0,51700.0,18822.0,3311.0,1863.0,0.0,20270.0,4241.0,16029.0,36.694748
2,2019,82675.0,62505.0,20170.0,2882.0,2011.0,0.0,21041.0,5631.0,15404.0,35.258303
3,2020,90791.0,68524.0,22267.0,2803.0,2893.0,170.0,22007.0,5368.0,16594.0,38.962198
4,2021,100472.0,72583.0,27889.0,2201.0,3267.0,195.0,26628.0,7205.0,19351.0,45.41742
5,2022,121641.0,90150.0,31491.0,2295.0,3476.0,200.0,30110.0,7964.0,22110.0,52.559013
6,2023,146767.0,111637.0,35130.0,2701.0,4225.0,284.0,33322.0,9214.0,24095.0,58.079834
7,2024,153670.0,117245.0,36425.0,4711.0,4678.0,470.0,35988.0,9740.0,26233.0,63.198343
8,2025,162990.0,123754.0,39236.0,3600.0,4812.0,416.0,37608.0,10858.0,26713.0,64.317531
9,2026,178650.0,136370.0,42280.0,3033.0,4902.0,416.0,39995.0,10521.0,29440.0,72.590985

In [ ]:
#@title Build Balance Sheet Dataset

balance_df = pd.DataFrame({

    "Year": balance_sheet.columns[1:],

    "Share_Capital": get_metric(balance_sheet, "Equity Share Capital").values,

    "Reserves": get_metric(balance_sheet, "Reserves").values,

    "Borrowings": get_metric(balance_sheet, "Borrowings").values,

    "Other_Liabilities": get_metric(balance_sheet, "Other Liabilities").values,

    "Total_Assets": get_metric(balance_sheet, "Total").values,

    "Net_Block": get_metric(balance_sheet, "Net Block").values,

    "CWIP": get_metric(balance_sheet, "Capital Work in Progress").values,

    "Investments": get_metric(balance_sheet, "Investments").values,

    "Other_Assets": get_metric(balance_sheet, "Other Assets").values,

    "Working_Capital": get_metric(balance_sheet, "Working Capital").values,

    "Receivables": get_metric(balance_sheet, "Debtors").values

})

balance_df

,Year,Share_Capital,Reserves,Borrowings,Other_Liabilities,Total_Assets,Net_Block,CWIP,Investments,Other_Assets,Working_Capital,Receivables
0,2017,1144.0,67838.0,0.0,14166.0,83148.0,14179.0,1365.0,16423.0,51181.0,37015.0,12322.0
1,2018,1088.0,63835.0,0.0,14426.0,79349.0,12574.0,1606.0,12163.0,53006.0,38580.0,13142.0
2,2019,2170.0,62778.0,0.0,19118.0,84066.0,15710.0,1388.0,11261.0,55707.0,36589.0,14827.0
3,2020,2122.0,63328.0,4633.0,21717.0,91800.0,23789.0,954.0,8792.0,58265.0,36548.0,18487.0
4,2021,2124.0,74227.0,5325.0,25835.0,107511.0,25505.0,922.0,14205.0,66879.0,41044.0,19294.0
5,2022,2098.0,73252.0,5474.0,35905.0,116729.0,25800.0,416.0,20324.0,70189.0,34284.0,22698.0
6,2023,2069.0,73338.0,8299.0,40890.0,124596.0,29225.0,288.0,19478.0,75605.0,34715.0,25424.0
7,2024,2071.0,86045.0,8359.0,39545.0,136020.0,27622.0,293.0,24623.0,83482.0,43937.0,30193.0
8,2025,2073.0,93745.0,8227.0,43750.0,147795.0,30961.0,814.0,23541.0,92479.0,48729.0,31158.0
9,2026,2024.0,90828.0,9176.0,52260.0,154288.0,33770.0,526.0,21880.0,98112.0,45852.0,35234.0

In [ ]:
#@title Build Cash Flow Dataset

cashflow_df = pd.DataFrame({

    "Year": cash_flow.columns[1:],

    "Operating_CF": get_metric(cash_flow, "Cash from Operating Activity").values,

    "Investing_CF": get_metric(cash_flow, "Cash from Investing Activity").values,

    "Financing_CF": get_metric(cash_flow, "Cash from Financing Activity").values,

    "Net_CF": get_metric(cash_flow, "Net Cash Flow").values

})

cashflow_df

   Year Operating_CF Investing_CF Financing_CF  Net_CF
0  2017        11531       -14664        -6939  -10072
1  2018        13218         4533       -20505   -2754
2  2019        14841         -632       -14512    -303
3  2020        17003         -331       -17591    -919
4  2021        23224        -7373        -9786    6065
5  2022        23885        -6485       -24642   -7242
6  2023        22467        -1071       -26695   -5299
7  2024        25210        -5093       -17504    2613
8  2025        35694        -1864       -24161    9669
9  2026        33986         3546       -39786   -2254

In [ ]:
#@title Verify Data Types

print(income_df.dtypes)

print()

print(balance_df.dtypes)

print()

print(cashflow_df.dtypes)

Year                  object
Revenue               object
Operating_Expenses    object
Operating_Profit      object
Other_Income          object
Depreciation          object
Interest              object
PBT                   object
Tax                   object
Net_Income            object
EPS                   object
dtype: object

Year                 object
Share_Capital        object
Reserves             object
Borrowings           object
Other_Liabilities    object
Total_Assets         object
Net_Block            object
CWIP                 object
Investments          object
Other_Assets         object
Working_Capital      object
Receivables          object
dtype: object

Year            object
Operating_CF    object
Investing_CF    object
Financing_CF    object
Net_CF          object
dtype: object

In [ ]:
#@title Save Clean Financial Tables

income_df.to_csv("income_statement.csv", index=False)

balance_df.to_csv("balance_sheet.csv", index=False)

cashflow_df.to_csv("cash_flow.csv", index=False)

print("Financial Data Warehouse Created Successfully!")

Financial Data Warehouse Created Successfully!