In [ ]:
#@title Import Libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

pd.set_option("display.max_columns", None)
pd.set_option("display.float_format", "{:,.2f}".format)

plt.style.use("ggplot")

In [ ]:
#@title Load Historical Financial Data

income_df = pd.read_csv("income_statement.csv")
balance_df = pd.read_csv("balance_sheet.csv")
cashflow_df = pd.read_csv("cash_flow.csv")

In [ ]:
#@title Historical Financial Summary

financials = pd.DataFrame({

    "Year": income_df["Year"],

    "Revenue": income_df["Revenue"],

    "Operating_Profit": income_df["Operating_Profit"],

    "Depreciation": income_df["Depreciation"],

    "Interest": income_df["Interest"],

    "PBT": income_df["PBT"],

    "Tax": income_df["Tax"],

    "Net_Income": income_df["Net_Income"],

    "Operating_CF": cashflow_df["Operating_CF"],

    "Borrowings": balance_df["Borrowings"],

    "Working_Capital": balance_df["Working_Capital"],

    "Total_Assets": balance_df["Total_Assets"],

    "Share_Capital": balance_df["Share_Capital"],

    "Reserves": balance_df["Reserves"]

})

financials

,Year,Revenue,Operating_Profit,Depreciation,Interest,PBT,Tax,Net_Income,Operating_CF,Borrowings,Working_Capital,Total_Assets,Share_Capital,Reserves
0,2017,"68,484.00","18,604.00","1,703.00",0.00,"19,951.00","5,598.00","14,353.00",11531,0.00,"37,015.00","83,148.00","1,144.00","67,838.00"
1,2018,"70,522.00","18,822.00","1,863.00",0.00,"20,270.00","4,241.00","16,029.00",13218,0.00,"38,580.00","79,349.00","1,088.00","63,835.00"
2,2019,"82,675.00","20,170.00","2,011.00",0.00,"21,041.00","5,631.00","15,404.00",14841,0.00,"36,589.00","84,066.00","2,170.00","62,778.00"
3,2020,"90,791.00","22,267.00","2,893.00",170.00,"22,007.00","5,368.00","16,594.00",17003,"4,633.00","36,548.00","91,800.00","2,122.00","63,328.00"
4,2021,"100,472.00","27,889.00","3,267.00",195.00,"26,628.00","7,205.00","19,351.00",23224,"5,325.00","41,044.00","107,511.00","2,124.00","74,227.00"
5,2022,"121,641.00","31,491.00","3,476.00",200.00,"30,110.00","7,964.00","22,110.00",23885,"5,474.00","34,284.00","116,729.00","2,098.00","73,252.00"
6,2023,"146,767.00","35,130.00","4,225.00",284.00,"33,322.00","9,214.00","24,095.00",22467,"8,299.00","34,715.00","124,596.00","2,069.00","73,338.00"
7,2024,"153,670.00","36,425.00","4,678.00",470.00,"35,988.00","9,740.00","26,233.00",25210,"8,359.00","43,937.00","136,020.00","2,071.00","86,045.00"
8,2025,"162,990.00","39,236.00","4,812.00",416.00,"37,608.00","10,858.00","26,713.00",35694,"8,227.00","48,729.00","147,795.00","2,073.00","93,745.00"
9,2026,"178,650.00","42,280.00","4,902.00",416.00,"39,995.00","10,521.00","29,440.00",33986,"9,176.00","45,852.00","154,288.00","2,024.00","90,828.00"

In [ ]:
#@title Historical Revenue Growth

financials["Revenue_Growth"] = (
    financials["Revenue"]
    .pct_change()
)

financials[["Year","Revenue","Revenue_Growth"]]

   Year    Revenue  Revenue_Growth
0  2017  68,484.00             NaN
1  2018  70,522.00            0.03
2  2019  82,675.00            0.17
3  2020  90,791.00            0.10
4  2021 100,472.00            0.11
5  2022 121,641.00            0.21
6  2023 146,767.00            0.21
7  2024 153,670.00            0.05
8  2025 162,990.00            0.06
9  2026 178,650.00            0.10

In [ ]:
#@title Historical Margins

financials["Operating_Margin"] = (
    financials["Operating_Profit"]
    / financials["Revenue"]
)

financials["Tax_Rate"] = (
    financials["Tax"]
    / financials["PBT"]
)

financials["Depreciation_Rate"] = (
    financials["Depreciation"]
    / financials["Revenue"]
)

financials

,Year,Revenue,Operating_Profit,Depreciation,Interest,PBT,Tax,Net_Income,Operating_CF,Borrowings,Working_Capital,Total_Assets,Share_Capital,Reserves,Revenue_Growth,Operating_Margin,Tax_Rate,Depreciation_Rate
0,2017,"68,484.00","18,604.00","1,703.00",0.00,"19,951.00","5,598.00","14,353.00",11531,0.00,"37,015.00","83,148.00","1,144.00","67,838.00",NaN,0.27,0.28,0.02
1,2018,"70,522.00","18,822.00","1,863.00",0.00,"20,270.00","4,241.00","16,029.00",13218,0.00,"38,580.00","79,349.00","1,088.00","63,835.00",0.03,0.27,0.21,0.03
2,2019,"82,675.00","20,170.00","2,011.00",0.00,"21,041.00","5,631.00","15,404.00",14841,0.00,"36,589.00","84,066.00","2,170.00","62,778.00",0.17,0.24,0.27,0.02
3,2020,"90,791.00","22,267.00","2,893.00",170.00,"22,007.00","5,368.00","16,594.00",17003,"4,633.00","36,548.00","91,800.00","2,122.00","63,328.00",0.10,0.25,0.24,0.03
4,2021,"100,472.00","27,889.00","3,267.00",195.00,"26,628.00","7,205.00","19,351.00",23224,"5,325.00","41,044.00","107,511.00","2,124.00","74,227.00",0.11,0.28,0.27,0.03
5,2022,"121,641.00","31,491.00","3,476.00",200.00,"30,110.00","7,964.00","22,110.00",23885,"5,474.00","34,284.00","116,729.00","2,098.00","73,252.00",0.21,0.26,0.26,0.03
6,2023,"146,767.00","35,130.00","4,225.00",284.00,"33,322.00","9,214.00","24,095.00",22467,"8,299.00","34,715.00","124,596.00","2,069.00","73,338.00",0.21,0.24,0.28,0.03
7,2024,"153,670.00","36,425.00","4,678.00",470.00,"35,988.00","9,740.00","26,233.00",25210,"8,359.00","43,937.00","136,020.00","2,071.00","86,045.00",0.05,0.24,0.27,0.03
8,2025,"162,990.00","39,236.00","4,812.00",416.00,"37,608.00","10,858.00","26,713.00",35694,"8,227.00","48,729.00","147,795.00","2,073.00","93,745.00",0.06,0.24,0.29,0.03
9,2026,"178,650.00","42,280.00","4,902.00",416.00,"39,995.00","10,521.00","29,440.00",33986,"9,176.00","45,852.00","154,288.00","2,024.00","90,828.00",0.10,0.24,0.26,0.03

In [ ]:
#@title Historical Forecast Drivers

drivers = pd.DataFrame({

    "Metric":[

        "Average Revenue Growth",

        "Average Operating Margin",

        "Average Tax Rate",

        "Average Depreciation Rate"

    ],

    "Historical Average":[

        financials["Revenue_Growth"].mean(),

        financials["Operating_Margin"].mean(),

        financials["Tax_Rate"].mean(),

        financials["Depreciation_Rate"].mean()

    ]

})

drivers["Historical Average"] *=100

drivers.round(2)

                      Metric  Historical Average
0     Average Revenue Growth               11.42
1   Average Operating Margin               25.18
2           Average Tax Rate               26.35
3  Average Depreciation Rate                2.85

In [ ]:
#@title Historical Forecast Drivers

drivers = pd.DataFrame({

    "Metric":[

        "Average Revenue Growth",

        "Average Operating Margin",

        "Average Tax Rate",

        "Average Depreciation Rate"

    ],

    "Historical Average":[

        financials["Revenue_Growth"].mean(),

        financials["Operating_Margin"].mean(),

        financials["Tax_Rate"].mean(),

        financials["Depreciation_Rate"].mean()

    ]

})

drivers["Historical Average"] *=100

drivers.round(2)

                      Metric  Historical Average
0     Average Revenue Growth               11.42
1   Average Operating Margin               25.18
2           Average Tax Rate               26.35
3  Average Depreciation Rate                2.85

#Forecast Assumptions

In [ ]:
#@title Forecast Assumptions

forecast = pd.DataFrame({

    "Year":[2027,2028,2029,2030,2031],

    "Revenue_Growth":[

        0.08,

        0.08,

        0.07,

        0.07,

        0.06

    ],

    "Operating_Margin":[

        0.24,

        0.24,

        0.245,

        0.245,

        0.25

    ],

    "Tax_Rate":[

        financials["Tax_Rate"].mean()

    ]*5,

    "Depreciation_Rate":[

        financials["Depreciation_Rate"].mean()

    ]*5

})

forecast

   Year  Revenue_Growth  Operating_Margin  Tax_Rate  Depreciation_Rate
0  2027            0.08              0.24      0.26               0.03
1  2028            0.08              0.24      0.26               0.03
2  2029            0.07              0.24      0.26               0.03
3  2030            0.07              0.24      0.26               0.03
4  2031            0.06              0.25      0.26               0.03

#Forecast Income Statement

In [ ]:
#@title Forecast Revenue

last_revenue = financials["Revenue"].iloc[-1]

revenues = []

current = last_revenue

for growth in forecast["Revenue_Growth"]:

    current *= (1 + growth)

    revenues.append(current)

forecast["Revenue"] = revenues

forecast

,Year,Revenue_Growth,Operating_Margin,Tax_Rate,Depreciation_Rate,Revenue
0,2027,0.08,0.24,0.26,0.03,"192,942.00"
1,2028,0.08,0.24,0.26,0.03,"208,377.36"
2,2029,0.07,0.24,0.26,0.03,"222,963.78"
3,2030,0.07,0.24,0.26,0.03,"238,571.24"
4,2031,0.06,0.25,0.26,0.03,"252,885.51"

In [ ]:
#@title Forecast Operating Profit (EBITDA)

forecast["EBITDA"] = (

    forecast["Revenue"]

    * forecast["Operating_Margin"]

)

forecast[["Year","Revenue","EBITDA"]]

   Year    Revenue    EBITDA
0  2027 192,942.00 46,306.08
1  2028 208,377.36 50,010.57
2  2029 222,963.78 54,626.12
3  2030 238,571.24 58,449.95
4  2031 252,885.51 63,221.38

In [ ]:
#@title Forecast Depreciation

forecast["Depreciation"] = (

    forecast["Revenue"]

    * forecast["Depreciation_Rate"]

)

forecast[["Year","Depreciation"]]

   Year  Depreciation
0  2027      5,494.15
1  2028      5,933.69
2  2029      6,349.04
3  2030      6,793.48
4  2031      7,201.09

In [ ]:
#@title Forecast EBIT

forecast["EBIT"] = (

    forecast["EBITDA"]

    - forecast["Depreciation"]

)

forecast[["Year","EBITDA","Depreciation","EBIT"]]

   Year    EBITDA  Depreciation      EBIT
0  2027 46,306.08      5,494.15 40,811.93
1  2028 50,010.57      5,933.69 44,076.88
2  2029 54,626.12      6,349.04 48,277.08
3  2030 58,449.95      6,793.48 51,656.48
4  2031 63,221.38      7,201.09 56,020.29

In [ ]:
#@title Forecast Interest Expense

average_interest_rate = (

    financials["Interest"]

    / financials["Borrowings"]

)

average_interest_rate = average_interest_rate.replace(

    [np.inf,-np.inf],

    np.nan

).mean()

forecast["Interest"] = (

    financials["Borrowings"].iloc[-1]

    * average_interest_rate

)

forecast[["Year","Interest"]]

   Year  Interest
0  2027    388.27
1  2028    388.27
2  2029    388.27
3  2030    388.27
4  2031    388.27

In [ ]:
#@title Forecast Profit Before Tax

forecast["PBT"] = (

    forecast["EBIT"]

    - forecast["Interest"]

)

forecast[["Year","PBT"]]

   Year       PBT
0  2027 40,423.65
1  2028 43,688.61
2  2029 47,888.81
3  2030 51,268.20
4  2031 55,632.02

In [ ]:
#@title Forecast Taxes

forecast["Tax"] = (

    forecast["PBT"]

    * forecast["Tax_Rate"]

)

forecast[["Year","Tax"]]

   Year       Tax
0  2027 10,653.11
1  2028 11,513.54
2  2029 12,620.45
3  2030 13,511.04
4  2031 14,661.07

In [ ]:
#@title Forecast Net Income

forecast["Net_Income"] = (

    forecast["PBT"]

    - forecast["Tax"]

)

forecast[["Year","Net_Income"]]

   Year  Net_Income
0  2027   29,770.54
1  2028   32,175.06
2  2029   35,268.36
3  2030   37,757.16
4  2031   40,970.95

In [ ]:
#@title Forecast Income Statement

forecast_income = forecast[[
    "Year",
    "Revenue",
    "EBITDA",
    "Depreciation",
    "EBIT",
    "Interest",
    "PBT",
    "Tax",
    "Net_Income"
]]

forecast_income.round(2)

,Year,Revenue,EBITDA,Depreciation,EBIT,Interest,PBT,Tax,Net_Income
0,2027,"192,942.00","46,306.08","5,494.15","40,811.93",388.27,"40,423.65","10,653.11","29,770.54"
1,2028,"208,377.36","50,010.57","5,933.69","44,076.88",388.27,"43,688.61","11,513.54","32,175.06"
2,2029,"222,963.78","54,626.12","6,349.04","48,277.08",388.27,"47,888.81","12,620.45","35,268.36"
3,2030,"238,571.24","58,449.95","6,793.48","51,656.48",388.27,"51,268.20","13,511.04","37,757.16"
4,2031,"252,885.51","63,221.38","7,201.09","56,020.29",388.27,"55,632.02","14,661.07","40,970.95"

#Forecast Balance Sheet

In [ ]:
#@title Historical Balance Sheet Drivers

financials["Debt_to_Revenue"] = (
    financials["Borrowings"] /
    financials["Revenue"]
)

financials["WC_to_Revenue"] = (
    financials["Working_Capital"] /
    financials["Revenue"]
)

financials["Asset_to_Revenue"] = (
    financials["Total_Assets"] /
    financials["Revenue"]
)

financials[[
    "Year",
    "Debt_to_Revenue",
    "WC_to_Revenue",
    "Asset_to_Revenue"
]]

   Year  Debt_to_Revenue  WC_to_Revenue  Asset_to_Revenue
0  2017             0.00           0.54              1.21
1  2018             0.00           0.55              1.13
2  2019             0.00           0.44              1.02
3  2020             0.05           0.40              1.01
4  2021             0.05           0.41              1.07
5  2022             0.05           0.28              0.96
6  2023             0.06           0.24              0.85
7  2024             0.05           0.29              0.89
8  2025             0.05           0.30              0.91
9  2026             0.05           0.26              0.86

In [ ]:
#@title Average Historical Drivers

debt_ratio = financials["Debt_to_Revenue"].mean()

wc_ratio = financials["WC_to_Revenue"].mean()

asset_ratio = financials["Asset_to_Revenue"].mean()

print(f"Debt / Revenue        : {debt_ratio:.3f}")
print(f"Working Capital Ratio : {wc_ratio:.3f}")
print(f"Asset Turnover Driver : {asset_ratio:.3f}")

Debt / Revenue        : 0.036
Working Capital Ratio : 0.370
Asset Turnover Driver : 0.990

In [ ]:
#@title Forecast Borrowings

forecast["Borrowings"] = (
    forecast["Revenue"]
    * debt_ratio
)

forecast[["Year","Borrowings"]]

   Year  Borrowings
0  2027    6,980.84
1  2028    7,539.30
2  2029    8,067.05
3  2030    8,631.75
4  2031    9,149.65

In [ ]:
#@title Recalculate Interest Expense

forecast["Interest"] = (
    forecast["Borrowings"]
    * average_interest_rate
)

forecast["PBT"] = (
    forecast["EBIT"]
    - forecast["Interest"]
)

forecast["Tax"] = (
    forecast["PBT"]
    * forecast["Tax_Rate"]
)

forecast["Net_Income"] = (
    forecast["PBT"]
    - forecast["Tax"]
)

forecast[[
    "Year",
    "Borrowings",
    "Interest",
    "Net_Income"
]]

   Year  Borrowings  Interest  Net_Income
0  2027    6,980.84    295.39   29,838.95
1  2028    7,539.30    319.02   32,226.07
2  2029    8,067.05    341.35   35,302.92
3  2030    8,631.75    365.24   37,774.12
4  2031    9,149.65    387.16   40,971.77

In [ ]:
#@title Forecast Working Capital

forecast["Working_Capital"] = (
    forecast["Revenue"]
    * wc_ratio
)

forecast[[
    "Year",
    "Working_Capital"
]]

   Year  Working_Capital
0  2027        71,409.84
1  2028        77,122.63
2  2029        82,521.21
3  2030        88,297.70
4  2031        93,595.56

In [ ]:
#@title Forecast Total Assets

forecast["Total_Assets"] = (
    forecast["Revenue"]
    * asset_ratio
)

forecast[[
    "Year",
    "Total_Assets"
]]

   Year  Total_Assets
0  2027    191,039.46
1  2028    206,322.62
2  2029    220,765.20
3  2030    236,218.77
4  2031    250,391.89

In [ ]:
#@title Forecast Retained Earnings

last_equity = (
    balance_df["Share_Capital"].iloc[-1]
    +
    balance_df["Reserves"].iloc[-1]
)

equity = []

current_equity = last_equity

for profit in forecast["Net_Income"]:

    current_equity += profit

    equity.append(current_equity)

forecast["Equity"] = equity

forecast[[
    "Year",
    "Equity"
]]

   Year     Equity
0  2027 122,690.95
1  2028 154,917.02
2  2029 190,219.93
3  2030 227,994.05
4  2031 268,965.83

In [ ]:
#@title Forecast Balance Sheet

forecast_balance = forecast[[
    "Year",
    "Borrowings",
    "Working_Capital",
    "Total_Assets",
    "Equity"
]]

forecast_balance.round(2)

   Year  Borrowings  Working_Capital  Total_Assets     Equity
0  2027    6,980.84        71,409.84    191,039.46 122,690.95
1  2028    7,539.30        77,122.63    206,322.62 154,917.02
2  2029    8,067.05        82,521.21    220,765.20 190,219.93
3  2030    8,631.75        88,297.70    236,218.77 227,994.05
4  2031    9,149.65        93,595.56    250,391.89 268,965.83